FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates tzdata wget \
    && rm -rf /var/lib/apt/lists/* \
    && update-ca-certificates

COPY .codex-tmp/one-api /one-api
EXPOSE 3000
WORKDIR /data
ENTRYPOINT ["/one-api"]
